version: '3'
secrets:
  my_secret_data:
    external: true

services:
  jenkins_server:
    image: "registry.jala.info/devops/jenkins/jenkins:2.107.3-alpine"
    secrets:
     - my_secret_data
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
  jenkins_slave:
   image: "registry.jala.info/devops/jenkins/jnlp-slave:3.27-1-alpine"
   environment:
     - -url
     - http://jenkins_server:50000
     - -workDir=/home/jenkins/agent
     - <cesar>
